# Generated by Django 4.2.7 on 2025-03-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_course_archived_coursereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereport',
            name='vote',
            field=models.CharField(choices=[('real', 'Course is real'), ('not_real', 'Course is not real')], default='not_real', max_length=10),
        ),
    ]
